spring.application.name=supportdesk-ai
spring.datasource.url=jdbc:mysql://localhost:3306/supportdesk
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true